### PR TITLE
added support for multiple batteries

### PR DESCRIPTION
**Pull request by fluktuid**
haven't seen multiple battery support for the batterybar, so I added it.

### CODE REVIEW

**Comment by fluktuid** [comment]
found a little bug ;-(

**Comment by kb100** [comment]
Go ahead and reopen if you fix the bug.

**Comment by fluktuid** [comment]
bugs fixed. ;-)

**Comment by kb100** [comment]
Hi, it looks fine to me except it looks like the indentation got messed up throughout. Could you please fix this and then squash your commits into one to make merging nice and easy for me? @snowlow could you also test @fluktuid's commit to make sure it works for your setup as well?

**Comment by snowiow** [comment]
Overall it's working fine for me. I don't know if we ever need to support 3 or more batteries, because this is limited to two. 
There is also one small bug in it:
The `acpi battery` gives following output:
```
Battery 0: Unknown, 95%
Battery 1: Discharging, 93%, 00:59:52 remaining
```
But the batterybar is showing the remaining time at the first battery:

screenshot_batterybar

**Comment by fluktuid** [comment]
Hopefully it is now fixed :crossed_fingers:

**Comment by kb100** [comment]
@fluktuid For some reason the diff contains new files for the temperature script? Please clean up the repo and squash the commits into one.

**Comment by fluktuid** [comment]
i fixed it, sorry
:man_facepalming: :gun:

**Comment by kb100** [comment]
@fluktuid viewing the file https://github.com/fluktuid/i3blocks-contrib/blob/8a364a287e892e2d2aac79a757982b4afda58712/batterybar/batterybar it still looks like the spacing is messed up. It looks like half the time tabs are used and half the time spaces are used. Either is fine but please make it consistent within the file.

**Comment by fluktuid** [comment]
Now hopefully everything is all right. :grimacing:

@kb100 I'm sorry, this is my very first pull request.

**Pull request closed without merging**
