### PR TITLE
mediaplayer: add rhythmbox support

### PR DESCRIPTION
**Pull request by cheukyin699**

### CODE REVIEW

**Comment by quinnuendo** [comment]
Isn't rhythmbox already available through MPRIS/DBUS?

**Comment by cheukyin699** [comment]
Oh. I thought it was a plugin or something.

**Comment by quinnuendo** [comment]
I haven't done a full test right now, but Rhythmbox does have MPRIS support, it might be through a plug-in, but I remember it working before.

Maybe a separate block with just Rhythmbox could make sense, for someone running just that program.

**Comment by cheukyin699** [comment]
Yup. It does have mpris support, and thus can be controlled through `playerctl`.

**Comment by kb100** [comment]
`playerctl` is an outside dependancy that rhythmbox users may not have already. It may make sense to include this PR anyway for that reason.

**Pull request merged**
