### PR TITLE
apt-upgrades, usb: minor maintenance and new config options

### PR DESCRIPTION
**Pull request by kb100**
Two commits, one for each blocklet.

### CODE REVIEW

**Comment by Nycroth** [comment]
USB looks fine. I can't check apt-upgrades though. I use pacman instead.

**Comment by kb100** [comment]
Does @vivien use apt? I hope I'm not the only user of my blocklets, though I may be the only one actively checking pull requests...

**Comment by vivien** [comment]
On Arch too... Looks fine to me anyway.

**Comment by jpleau** [comment]
@kb100 I actually have been using two of your blocklets: apt-upgrades and usb. They are both working great on my desktop (running Debian sid) :)

Sorry for the lack of feedback, I have been busy with lots of stuff, should be back to normal once winter starts !

**Comment by Nycroth** [comment]
No worries @jpleau. :+1:

**Pull request merged**
