### PR TITLE
Batterybar: add time remaining on click

### PR DESCRIPTION
**Pull request by lathan**
Hello!

Really cool blocklet. I feel it was missing the time remaining value, which the main battery blocklet has, so here's my pull request.

Cheers

### CODE REVIEW

**Comment by lathan** [comment]
I'm not sure what happens to time remaining when the battery is full. I would need to check that.

**Comment by lathan** [comment]
Also, I would like to retain the awesome colors in "text mode", for example:

batterybar

**Comment by lathan** [comment]
ok so here's what happens with a full battery:

```
$ acpi
Battery 0: Full, 100%
```
As a result, since I've hardcoded the parenthesis in the output, the output on the bar is:  
`Full 100% ()`
That's silly. The parentheses should go away in this case.

**Comment by lathan** [comment]
squashed and force-pushed. Now, time remaining along with its parentheses only appear when applicable.

Waiting for comments now. :)

**Comment by Nycroth** [comment]
Sorry @lathan. I've been pretty busy with the start of school. I'll play with this script within a few hours and post back.

**Comment by Keftaa** [comment]
Hey @lathan , feels good to have my first script on GitHub running on another computer !

Confirmed working with laptops that don't have time remaining information (such as mine).

**Comment by lathan** [comment]
@Keftaa my regex-foo isn't strong, so I lazily mimicked [this](https://github.com/vivien/i3blocks/blob/master/scripts/battery#L48). :smile:

**Comment by vivien** [comment]
Commit messages are clean too! @Nycroth feel free to merge this when you're satisfied :-)

**Comment by lathan** [comment]
ty @vivien @Nycroth @Keftaa !

**Comment by Nycroth** [comment]
No no. Thank you for the patch! :smile:

**Pull request merged**
