### PR TITLE
mediaplayer: Output newline at end

### PR DESCRIPTION
**Pull request by Aster89**

### CODE REVIEW

**Comment by kb100** [comment]
Looks good to me. I don't use this block so can you confirm that you tested it?

**Comment by Aster89** [comment]
I confirm it works for `playerctl`. Since all the alternatives should be coherent (in terms of missing newlines), I'd say it just work anyway.

**Comment by kb100** [comment]
Great, thanks for this one!

**Comment by Aster89** [comment]
Just out of curiosity, what should the output be when Spotify (or whatever) is not running?

**Comment by kb100** [comment]
I think the block should be transparent if the player is not running.

**Pull request merged**
