### PR TITLE
Batterybar fix, handle empty ACPI output

### PR DESCRIPTION
**Pull request by kb100**
fixes https://github.com/vivien/i3blocks-contrib/issues/28

### CODE REVIEW

**Comment by kb100** [comment]
Any idea why it is showing that previous commit? My commit is only the batterybar one.

**Comment by kb100** [comment]
There we go, I just needed to rebase onto the upstream...

**Comment by jpleau** [comment]
@kb100 

If I run this on a desktop, is this the expected behavior? I don't have a laptop or anything with a battery this is all I can test :(

http://i.imgur.com/SPk1GfA.png (the red part on the right)

**Comment by kb100** [comment]
AFAIK yes that is what the author intended. it's not the most pleasing looking IMO.

**Comment by kb100** [comment]
Can the author @lathan comment?

**Comment by lathan** [comment]
Sorry for the late response.
* I'm not the original author.
* I made some changes recently but never tested on desktop or generally without acpi installed.

**Comment by lathan** [comment]
I don't have any suggestions beyond this.

**Pull request closed without merging**
