### PR TITLE
Add missing dependency in arch-update script

### PR DESCRIPTION
**Pull request by joelwurtz**

### CODE REVIEW

**Comment by jolange** [comment]
This was actually included in the next branch already: 7c1ec53

**Comment by joelwurtz** [comment]
Didn't know there was a next branch, you can revert this then

**Comment by jolange** [comment]
It's not a problem, no need to revert ;-) Will just need to be merged at some point

**Comment by kb100** [comment]
I actually merged this, forgetting that I had already merged a similar PR into the next branch and fixed it up in the next branch. I think this was an important one to merge into the master branch immediately though because if a user doesn't have the right deps then the whole block is unusable.

**Pull request merged**
