### PR TITLE
timer_and_stopwatch: minimal stopwatch and colored timer

### PR DESCRIPTION
**Pull request by Aster89**
@kb100, in response to issue [#208](https://github.com/vivien/i3blocks-contrib/issues/208), I coded this minimal stopwatch and timer blocklet. 

The timer has also a (hard-coded) coloring that goes linearly from green to red.

I've also added a variable to make the timer loop around. I think it's useful when you have, say, X questions you should answer in Y seconds; you can put the timer at Y/X and it will track the time per question.

Let me know if I can improve it.

### CODE REVIEW

**Comment by da-edra** [comment]
Hello @Aster89 I know it's been a while since you opened this PR, I'd like to integrate it into a fork we're creating to keep the [i3blocks-contrib](https://github.com/da-edra/i3blocks-contrib) repository updated.

You PR looks pretty good! It is a nice and useful block, in case you're still using i3blocks and interested in it getting merged could you please fix the following errors [shellcheck](https://github.com/koalaman/shellcheck) found?

```bash
In timer.sh line 24:
    $running && pause || play
             ^-- SC2015: Note that A && B || C is not if-then-else. C may run when A is true.


In timer.sh line 64:
    hue360=$(( 120*$t/$initial_time ))
                   ^-- SC2004: $/${} is unnecessary on arithmetic variables.
                      ^-----------^ SC2004: $/${} is unnecessary on arithmetic variables.


In timer.sh line 98:
    for i in ${!modes[@]}; do
             ^----------^ SC2068: Double quote array expansions to avoid re-splitting elements.


In timer.sh line 156:
echo '{"full_text":"'$full_text'"' \
                     ^--------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
echo '{"full_text":"'"$full_text"'"' \


In timer.sh line 157:
     ',"status_symbol":"'$status_symbol'"' \
                         ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
     ',"status_symbol":"'"$status_symbol"'"' \


In timer.sh line 162:
     ',"mode":"'$mode'"'    \
                ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
     ',"mode":"'"$mode"'"'    \

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
  https://www.shellcheck.net/wiki/SC2015 -- Note that A && B || C is not if-t...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

Thanks in advance!

**Comment by Aster89** [comment]
Yes, I'm still using this `i3blocks` and I'll give a look at this blocklet asap.

**Comment by Aster89** [comment]
Ok, @da-edra , so I've used `cat` with a "here document" in place of `echo`/`printf` for printing the JSON line so I could save several characters and quotes.

I've skipped only one of those `spellcheck` "suggestions", for this reason: both `play()` and `pause()` functions just set the variable `running` to `true`/`false` (and there's no way this can fail, is there?), and the variable `status_symbol` to a value to be set from `i3blocks`'s config file. This is to say that I can't see how, in this case, `A && B || C` could behave differently from _if-then-else_. Spelling out the latter would mean either 5 lines or a very ugly single line.

**Comment by Aster89** [comment]
@da-edra , I think you might have erroneously commented the wrong PR. Maybe you ment to comment #213 ?

**Pull request merged**
