### PR TITLE
arch-update: add --hide option

### PR DESCRIPTION
**Pull request by jolange**
option `-H/--hide`: produces no output if no updates available

@snowiow: Since this is completely your work up to now, you might want to add your two cents about this change.

### CODE REVIEW

**Comment by snowiow** [comment]
Hi, thanks for your contribution. I would call the option quiet. Then you can use -q as the short argument. That way it would be more distinct from the help option. Beside of that it looks good to me.

**Comment by jolange** [comment]
> I would call the option quiet.

Also fine with me, changed.

**Comment by kb100** [comment]
Thanks for this.

**Comment by jolange** [comment]
Wow, that was fast ;-)

**Comment by kb100** [comment]
Commit was very straightforward so it was easy to review :) Also I added the quiet option to the README

**Comment by jolange** [comment]
Ah thanks, I forgot that!

**Pull request merged**
