### PR TITLE
keyindicator: customizable ON/OFF strings

### PR DESCRIPTION
**Pull request by Aster89**
To address my own proposal in #212.

### CODE REVIEW

**Comment by kb100** [comment]
Please make the default behavior to do exactly what the current script does so we don't break anyone's bar.

**Comment by kb100** [comment]
Meaning the defaults should not have fontawesome lock icons, and the default config also does not use locks icons.

**Comment by Aster89** [comment]
Doesn't it? Each of the two variables I've added default to `BLOCK_INSTANCE` or `KEY`, if they're not provided in the i3blocks configuration file.

**Comment by Aster89** [comment]
I've commented the two configuration lines, if that is what you implied.

**Comment by Aster89** [comment]
@kb100, I think it should be ok, now, no?

**Comment by da-edra** [comment]
Hello @Aster89 I know it's been a while since you opened this PR, I'd like to integrate it into a fork we're creating to keep the [i3blocks-contrib](https://github.com/da-edra/i3blocks-contrib) repository updated.

You PR looks pretty good! It is a nice and useful block, in case you're still using i3blocks and interested in it getting merged could you please fix the following errors [perl critic](https://metacpan.org/release/Perl-Critic) found?

```bash
Bareword file handle opened at line 64, column 1.  See pages 202,204 of PBP.  (Severity: 5)
Two-argument "open" used at line 64, column 1.  See page 207 of PBP.  (Severity: 5)
```

Thanks in advance!

**Comment by Aster89** [comment]
Hi @da-edra. Unfortunately my `perl` is not good enough to take this on, at the moment. That line existed before I worked on this PR, however, and my edits were only some copy and paste.

**Comment by Aster89** [comment]
@da-edra , license added.

**Pull request merged**
