### PR TITLE
key_layout optimization

### PR DESCRIPTION
**Pull request by METAJIJI**
Minimizing the pipes, and system calls. There was only awk and no bash.

### CODE REVIEW

**Comment by kb100** [comment]
Hi, would it be possible to measure performance increase? Like run the block a large number of times each way and compute the average execution time. (I don't know exactly what I'm asking for here so it's a learning process for me too) Also, I think your `if, if` blocks might benefit from being `if, else if`.

**Comment by METAJIJI** [comment]
Exaple simple tests:
```
$ time bash new.sh 
us,ru,
real	0m0.011s
user	0m0.004s
sys	0m0.005s

$ time bash old.sh 
us,ru ,

real	0m0.017s
user	0m0.009s
sys	0m0.010s
```
`new.sh` is faster, because `setxkbmap` run only once and run only alone `awk`.
`old.sh` is slow, because `setxkbmap` and awk run at 2 times and `tr`.

Also `new.sh` fix the trailing space after `us,ru`.

Added performance is very small, but it is more the right way.

**Comment by kb100** [comment]
I like the idea but the code looks a little clumsy. What do you think about

    setxkbmap -query | awk '
        BEGIN{layout="";variant=""}
        /^layout/{layout=$2}
        /^variant/{variant=$2}
        END{printf("%s%s",layout,variant)}
    '

**Comment by METAJIJI** [comment]
Yes, this is good variant! I'm create new commit.

**Comment by kb100** [comment]
Ready to merge, please squash the two commits into one and make the commit title of the form

    key_layout: optimize by calling programs only once

**Comment by METAJIJI** [comment]
Done!

**Comment by kb100** [comment]
Thanks for your contribution!

**Pull request merged**
