### PR TITLE
xkb_layout: a simple keyboard layout indicator persistent block

### PR DESCRIPTION
**Pull request by skidnik**
Uses xkb-switch to output current layout, infinitely waits for layout change then outputs the new one. Does not require signals to refresh (binding to ISO_NEXT_GROUP works weird and unreliable), does not require additional daemons to run.

### CODE REVIEW

**Comment by da-edra** [comment]
Hello @skidnik , thank you very much for your pull request!

This blocket looks pretty good and it seems pretty useful, I've integrated it to my [i3blocks-contrib](https://github.com/da-edra/i3blocks-contrib) fork where I'll keep the repository updated in case you want to check it out!

**Comment by da-edra** [comment]
Hey @skidnik , I now have write access to this repository so I'll be merging your branch.

**Comment by skidnik** [comment]
Thank you for stepping out and maintaining this repository. Look forward to an 1.5 release creation so that I could try to package it properly for Fedora and Arch.

**Comment by da-edra** [comment]
@skidnik yes, I have plans for a new release, I just need to fix some things before releasing it, I'll let you know once it's ready. :)

**Pull request merged**
