### PR TITLE
key_layout: Fix detect layout on multilingual

### PR DESCRIPTION
**Pull request by METAJIJI**
Change detect method from `setxkbmap` to `xset -q`, because `setxkbmap`  can not detect when more than one keyboard layouts.

### CODE REVIEW

**Comment by METAJIJI** [comment]
But previous code show only `us,ru,winkeys`, and this not informative.
I think display the keyboard layout is much more useful.

And new code is show `us` or `ru` or `other` and this more informative also i never seen `winkeys` and similar in regular OS (win, mac, linux, etc), may be drop this feature? How use `winkeys`?

**Comment by jolange** [comment]
> But previous code show only us,ru,winkeys, and this not informative.

I don't see what you mean. The current script shows whatever setxkbmap returns (in my case `de`), which exacly what it should do, right?

> And new code is show us or ru or other

In my case it shows `en` instead of `de`.

**Comment by METAJIJI** [comment]
First set multiple keyboard layouts and set switch shortcut Alt+Shift (in my case):

`setxkbmap "us,ru" ",winkeys" "grp:alt_shift_toggle"`

Then run script and see:
```
$ ./key_layout
us,ru,winkeys
```

Switch between layouts (Press Alt+Shift) does not change the output `key_layout`.

**Comment by jolange** [comment]
Ah, I see your problem. I did not know that toggle mechanism.

Still, your code does not work generically, see also the comments [here](http://unix.stackexchange.com/questions/12072/how-do-i-get-current-keyboard-layout/27688#27688).

**Comment by METAJIJI** [comment]
I see this thread and write awk function for workaround this and now my code is work with caps and num lock if you mean this point :)

**Comment by jolange** [comment]
Maybe this might be interesting for you: https://github.com/nonpop/xkblayout-state

**Comment by kb100** [comment]
Keyboard layout is, for some reason, one of those things that has not been properly unified in linux yet. As such, "getting the current layout" is undefined and many programs do it in different ways and give different results. In this repo, we have two blocks, key_layout, and kbdd_layout, and possibly another in https://github.com/vivien/i3blocks-contrib/pull/77 soon. If you are toggling using layout groups, then use kbdd_layout, which handles this properly.

**Pull request closed without merging**
