### PR TITLE
Add LICENSE.md to repo

### PR DESCRIPTION
**Pull request by Nycroth**
Noted the license wasn't in the repo, I've just copied it from the wiki. I assume the project is also GPLv3 like i3blocks.

### CODE REVIEW

**Comment by jpleau** [comment]
Question: should we allow blocklets with licenses that are not compatible with GPLv3 ? 

ie: http://www.gnu.org/licenses/license-list.en.html#GPLIncompatibleLicenses

**Comment by Nycroth** [comment]
I've no horse. I personally don't believe in intelectual property.

This is something Vivien will have decide.

**Comment by kb100** [comment]
I think any free software license should be acceptable. Let the content creator decide how to license his or her code. As long as someone else's license doesn't negatively affect me, I don't have any issue with my code being in the same repository as theirs. Since we allow multiple blocklets that accomplish the same task, in the event of a true conflict of interest in deciding the license of a blocklet, the blocklet can simply be forked or rewritten under another license.

That said, if in the future we decide that i3blocks-contrib should be packaged, e.g., for debian, then we will need to be stricter about what licenses are allowed, or the maintainer will have to exclude those blocklets do not conform to the distro's licensing standards. The maintainer could also package conforming packages into i3blocks-contrib and nonconforming packages into i3blocks-nonfree.

**Comment by jpleau** [comment]
@kb100 That was the reason why I was mentionning this ;)

I planned to package i3blocks-contrib soon  [1] for Debian / Ubuntu, I
don't think licenses will be an issue however. Mixing GPL-licensed scripts
with other BSD-licensed scripts for example wouldn't cause problems,
there's no linkage involved. I would like to avoid having to package a
non-free version of i3blocks-nonfree, for simplicity's sake

1. Most likely when i3blocks-1.5 and i3blocks-contrib-1.5 are released :)

2015-10-06 18:15 GMT-04:00 kb100 <notifications@github.com>:

**Comment by vivien** [comment]
Same as @jpleau. I don't mind multiple licenses, but:
1. I would strongly recommend free (as in **GPL**) software ;-)
2. I want to make it simple for packagers.

**Comment by Nycroth** [comment]
Just changed the license intro. If this change is accepted, we had best update the `CONTRIBUTING.md` guidelines.

**Comment by Nycroth** [comment]
Is anyone opposed to merging this?

**Comment by kb100** [comment]
Looks good to me, squash and merge.

**Comment by Nycroth** [comment]
Merged.

**Pull request closed without merging**
