### PR TITLE
key_light: add script to control keyboard backlight

### PR DESCRIPTION
**Pull request by mathewcohle**

### CODE REVIEW

**Comment by mathewcohle** [comment]
@kb100 Hi, is this repo still maintained? Looks like nothing has been merged past couple of months.

**Comment by da-edra** [comment]
Hello @mathewcohle I know it's been a while since you opened this PR, I'd like to integrate it into a fork we're creating to keep the [i3blocks-contrib](https://github.com/da-edra/i3blocks-contrib) repository updated.

You PR looks pretty good! It is a nice and useful block, in case you're still using i3blocks and interested in it getting merged could you please fix the following errors [shellcheck](https://github.com/koalaman/shellcheck) found?

```bash
In keylight line 20:
    echo $(dbus-send --system --type=method_call --print-reply\
         ^-- SC2046: Quote this to prevent word splitting.
         ^-- SC2005: Useless echo? Instead of 'echo $(cmd)', just use 'cmd'.


In keylight line 30:
if [ $brightness -eq $max_brightness ]; then
     ^---------^ SC2086: Double quote to prevent globbing and word splitting.
                     ^-------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
if [ "$brightness" -eq "$max_brightness" ]; then

For more information:
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
  https://www.shellcheck.net/wiki/SC2005 -- Useless echo? Instead of 'echo $(...
```

Thanks in advance!

**Comment by mathewcohle** [comment]
Hi @da-edra, even though I've migrated to different status bar manager, I will gladly resolve that error and push the fix so `key_light` might be merged. Glad to hear i3block-contrib is not dead :)

**Comment by mathewcohle** [comment]
@da-edra PR opened: https://github.com/da-edra/i3blocks-contrib/pull/1

Btw thanks for the `shellcheck` tip, looks like a lovely tool :)

**Comment by da-edra** [comment]
Hello @mathewcohle !

I now have write access to this repository! :tada: 

I tested your blocklet and I can confirm it works and since it pass the shellcheck tests I'll be merging your branch.

Thank you very much for sharing your blocklet with us! :1st_place_medal:

**Pull request merged**
